###
POST http://localhost:5000/createJob
Content-Type: application/json

[
    {
        "JOB_CODE": "ANGGOTA",
        "JOB_DESC": "Anggota Adalah KOperasi"
    },
    {
        "JOB_CODE": "PENGURUS",
        "JOB_DESC": "Pengurus Adalah KOperasi"
    },
        {
        "JOB_CODE": "ADMIN",
        "JOB_DESC": "Pengelola konfigurasi web"
    }
]

### Create Default MS_STATUS_PINJAMAN Data
POST http://localhost:5000/createStatus/PINJAMAN
Content-Type: application/json

[
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ACTIVE",
        "STATUS_NAME": "Aktif",
        "STATUS_DESC": "Pengajuan sedang aktif dan belum di proses."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "APPROVED",
        "STATUS_NAME": "Disetujui",
        "STATUS_DESC": "Pengajuan sudah disetujui."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "DECLINED",
        "STATUS_NAME": "Ditolak",
        "STATUS_DESC": "Pengajuan sudah ditolak."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ABORTED",
        "STATUS_NAME": "Dibatalkan",
        "STATUS_DESC": "Pengajuan dibatalkan."
    }
]

### Create Default MS_STATUS_PINJAMAN Data
POST http://localhost:5000/createStatus/SIMPANAN
Content-Type: application/json

[
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ACTIVE",
        "STATUS_NAME": "Aktif",
        "STATUS_DESC": "Pengajuan sedang aktif dan belum di proses."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "APPROVED",
        "STATUS_NAME": "Disetujui",
        "STATUS_DESC": "Pengajuan sudah disetujui."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "DECLINED",
        "STATUS_NAME": "Ditolak",
        "STATUS_DESC": "Pengajuan sudah ditolak."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ABORTED",
        "STATUS_NAME": "Dibatalkan",
        "STATUS_DESC": "Pengajuan dibatalkan."
    }
]

### Create Default MS_TYPE_PINJAMAN Data
POST http://localhost:5000/createType/PINJAMAN
Content-Type: application/json

[
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "KPKA",
        "TYPE_DESC": "Kredit Pelayanan Khusus Anggota",
        "TENOR":1,
        "INTEREST_RATE": 5,
        "MINIMUM_PINJAMAN": 500000,
        "MAXIMUM_PINJAMAN": 10000000
    },
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "UKSP",
        "TYPE_DESC": "Usaha Kredit Simpan Pinjam",
        "TENOR": 3,
        "INTEREST_RATE": 5,
        "MINIMUM_PINJAMAN": 10000001,
        "MAXIMUM_PINJAMAN": 100000000
    },
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "UKTP",
        "TYPE_DESC": "Usaha Kredit Tunjangan Profesi",
        "TENOR": 5,
        "INTEREST_RATE": 5,
        "MINIMUM_PINJAMAN": 100000001,
        "MAXIMUM_PINJAMAN": 1000000000
    }
]

### Create Default MS_TYPE_SIMPANAN Data
POST http://localhost:5000/createType/SIMPANAN
Content-Type: application/json

[
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "Simpanan Sukarela",
        "TYPE_DESC": "Simpanan tidak wajib setiap anggota.",
        "INTEREST_RATE": 5,
        "MINIMUM_SIMPANAN": 500000,
        "MAXIMUM_SIMPANAN": 10000000,
        "IS_MANDATORY": 0,
        "IS_AUTO_APPROVE": 1
    },
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "Simpanan Wajib",
        "TYPE_DESC": "Simpanan wajib setiap anggota.",
        "INTEREST_RATE": 5,
        "IS_MANDATORY": 1,
        "DEFAULT_NOMINAL": 50000,
        "IS_AUTO_APPROVE": 1
    }
]

### Create TR_PENGAJUAN_PINJAMAN dummy 1
POST http://localhost:5000/TR_PENGAJUAN_PINJAMAN/createPengajuanPinjaman
Content-Type: application/json

{
    "UUID_MS_USER": 1,
    "UUID_MS_STATUS_PINJAMAN": 1,
    "UUID_MS_TYPE_PINJAMAN": 1,
    "USR_CRT": "admin",
    "NOMINAL": 850000,
    "REASON": "Kepingin aja pinjem gituh.."
}

### Create TR_PENGAJUAN_PINJAMAN dummy 2
POST http://localhost:5000/TR_PENGAJUAN_PINJAMAN/createPengajuanPinjaman
Content-Type: application/json

{
    "UUID_MS_USER": 2,  
    "UUID_MS_STATUS_PINJAMAN": 1,
    "UUID_MS_TYPE_PINJAMAN": 3,
    "USR_CRT": "admin",
    "NOMINAL": 3000000,
    "REASON": "Lorem Ipsum Ahh description, i like my cheese drippy bruh, ohio looksmaxxing sigma boutta bust! gyatt look at shawty like im kai cenat, livvy dunne be like skibidi rizz."
}

### Create TR_PENGAJUAN_PINJAMAN dummy 3
POST http://localhost:5000/TR_PENGAJUAN_PINJAMAN/createPengajuanPinjaman
Content-Type: application/json

{
    "UUID_MS_USER": 3,  
    "UUID_MS_STATUS_PINJAMAN": 1,
    "UUID_MS_TYPE_PINJAMAN": 2,
    "USR_CRT": "admin",
    "NOMINAL": 15000000,
    "REASON": "OGH MAI GAD TESTING"
}