GET http://localhost:5000/TR_PENGAJUAN_PINJAMAN

###
GET http://localhost:5000/MS_STATUS_PINJAMAN

###
GET http://localhost:5000/MS_TYPE_PINJAMAN

### Create Default MS_STATUS_PINJAMAN Data
POST http://localhost:5000/MS_STATUS_PINJAMAN
Content-Type: application/json

[
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ACTIVE",
        "STATUS_NAME": "Aktif",
        "STATUS_DESC": "Pengajuan sedang aktif dan belum di proses."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "APPROVED",
        "STATUS_NAME": "Disetujui",
        "STATUS_DESC": "Pengajuan sudah disetujui."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "DECLINED",
        "STATUS_NAME": "Ditolak",
        "STATUS_DESC": "Pengajuan sudah ditolak."
    },
    {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ABORTED",
        "STATUS_NAME": "Dibatalkan",
        "STATUS_DESC": "Pengajuan dibatalkan."
    }
]

### Create Default MS_TYPE_PINJAMAN Data
POST http://localhost:5000/MS_TYPE_PINJAMAN
Content-Type: application/json

[
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "KPKA",
        "TYPE_DESC": "Kredit Pelayanan Khusus Anggota",
        "ANGSURAN_MONTH": 36,
        "MINIMUM_PINJAMAN": 1000000,
        "MAXIMUM_PINJAMAN": 10000000
    },
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "UKSP",
        "TYPE_DESC": "Usaha Kredit Simpan Pinjam",
        "ANGSURAN_MONTH": 24,
        "MINIMUM_PINJAMAN": 10000001,
        "MAXIMUM_PINJAMAN": 100000000
    },
    {    
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "TYPE_NAME": "UKTP",
        "TYPE_DESC": "Usaha Kredit Tunjangan Profesi",
        "ANGSURAN_MONTH": 12,
        "MINIMUM_PINJAMAN": 100000001,
        "MAXIMUM_PINJAMAN": 1000000000
    }
]

### Create TR_PENGAJUAN_PINJAMAN dummy
POST http://localhost:5000/TR_PENGAJUAN_PINJAMAN
Content-Type: application/json

{
    "UUID_MS_STATUS_PINJAMAN": 1,
    "UUID_TYPE_PINJAMAN": 1,
    "USR_CRT": "johnnydummy123@dummy.com",
    "NAMA_LENGKAP": "Dummy Johnny",
    "ALAMAT": "Jalan Dummy, Block 12, Lantai 326 Lt. Street",
    "NOMOR_TELEPON": "0819588436",
    "UNIT_KERJA": "Sekolah",
    "NOMOR_ANGGOTA": "D5MMY-153023",
    "NOMINAL_UANG": 850000,
    "DESKRIPSI": "Kepingin aja pinjem gituh.."
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Nikolas Febrisan",
    "email": "nikolasfeber@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users