GET http://localhost:5000/TR_PENGAJUAN_PINJAMAN

###
GET http://localhost:5000/MS_STATUS_PINJAMAN/1

###
POST http://localhost:5000/TR_PENGAJUAN_PINJAMAN
Content-Type: application/json

{
    "statusData": {
        "IS_ACTIVE": 1,
        "IS_DELETED": 0,
        "USR_CRT": "admin",
        "STATUS_CODE": "ACTIVE",
        "STATUS_NAME": "Active Status",
        "STATUS_DESC": "The status is currently active."
    },
    "pengajuanData": {
        "USR_CRT": "admin"
        // Include other necessary fields for TR_PENGAJUAN_PINJAMAN
    }
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Nikolas Febrisan",
    "email": "nikolasfeber@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users